# Generated by Django 4.2.6 on 2023-10-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character_Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characters_comparing', models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker_Extraction_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, max_length=30, null=True)),
                ('channel_image', models.CharField(blank=True, max_length=80, null=True)),
                ('ticker_image', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.CharField(blank=True, max_length=15, null=True)),
                ('time', models.CharField(blank=True, max_length=12, null=True)),
                ('text_ocr', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='words_to_be_searched_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
